---
- hosts: all
  gather_facts: yes
  become: true

  tasks:
    - name: install nginx
      apt:
        name: nginx
        state: latest
        
    - name: start the nginx server
      service:
        name: nginx
        state: started
        enabled: yes
