---
- name: install packages
  include_tasks: install.yaml

- name: update replication configuration
  include_tasks: update_replication_cfg.yaml

- name: init replicaset
  include_tasks: init_replicaset.yaml