#!/bin/bash
sudo apt install git -y
sudo curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
sudo python3 get-pip.py
sudo python3 -m pip install ansible
git clone https://github.com/s2zaman/devops_assignment.git /tmp/devops-assignment
/usr/local/bin/ansible-playbook -i /tmp/devops-assignment/ansible/hosts /tmp/devops-assignment/ansible/app_server_cfg.yaml